DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;

CREATE TABLE course
(
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL DEFAULT '',
    start_date date         NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE student
(
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL DEFAULT '',
    last_name  VARCHAR(255) NOT NULL DEFAULT '',
    course_id  BIGINT       NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE TABLE users
(
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(128) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    active      INT          NOT NULL DEFAULT 1,
    roles       VARCHAR(255) NOT NULL DEFAULT '',
    permissions VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);

INSERT INTO users (username, password, active, roles, permissions)
VALUES ('testing', '{noop}123qwe123', 1, 'USER', 'USER'),
       ('guest', '{noop}123qwe123', 1, 'GUEST', 'GUEST'),
       ('admin', '{noop}123qwe123', 1, 'ADMIN', 'ADMIN');

INSERT INTO course (name, start_date)
VALUES ('Java', '2020-01-01'),
       ('Python', '2020-02-01'),
       ('QA', '2020-03-01'),
       ('Cybersecurity', '2020-04-01'),
       ('DevOps', '2020-05-01');
