DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;

CREATE TABLE course
(
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL DEFAULT '',
    start_date date         NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE student
(
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL DEFAULT '',
    last_name  VARCHAR(255) NOT NULL DEFAULT '',
    course_id  BIGINT       NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);

INSERT INTO course (name, start_date)
VALUES ('Java', '2020-01-01'),
       ('Python', '2020-02-01'),
       ('QA', '2020-03-01'),
       ('Cybersecurity', '2020-04-01'),
       ('DevOps', '2020-05-01');
